############################################################
#                                                          #
#              authentication services config              #
#                                                          #
############################################################
parameters:
  # authentication success handler class
  authentication_emmobilier_login_handler_class:    'App\Security\LoginSuccessHandler\EmmobilierLoginSuccessHandler'
  authentication_admin_login_handler_class:         'App\Security\LoginSuccessHandler\AdminLoginSuccessHandler'
  authentication_residence_login_handler_class:     'App\Security\LoginSuccessHandler\ResidenceLoginSuccessHandler'
  authentication_logout_handler_class:              'App\Security\SessionLogoutHandler'
# Services configuration
services:
  # explicitly configure the services

  # authentication logout success handler
  authentication_logout_success_handler:
    class:                      '%authentication_logout_handler_class%'
    autowire:                   true
  # authentication login success handler
  authentication_emmobilier_login_success_handler:
    class:                      '%authentication_emmobilier_login_handler_class%'
    autowire:                   true
    tags:
    - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
  authentication_admin_login_success_handler:
    class:                      '%authentication_admin_login_handler_class%'
    autowire:                   true
    calls:
      - method: setUserInChargeOnTheOrderSection
        arguments:
          - '%user_in_charge_on_the_order_section%'
    tags:
    - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
  authentication_residence_login_success_handler:
    class:                      '%authentication_residence_login_handler_class%'
    autowire:                   true
    tags:
    - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
  # providers
  user_provider.username_email.admin: '@App\Security\Providers\AdminProvider'
  user_provider.username_email.emmobilier: '@App\Security\Providers\EmmobilierProvider'
  user_provider.username_email.residence: '@App\Security\Providers\ResidenceProvider'