framework:
    assets:
        version: '%asset_version%'
        packages:
            # emmobilier static files
            local_css:
                base_path: 'assets/emmobilier/css'
            local_js:
                base_path: 'assets/emmobilier/js'
            local_icons:
                base_path: 'assets/emmobilier/icons'
            # admin static files
            admin_css:
                base_path:  'assets/admin/css'
            admin_fonts:
                base_path:  'assets/admin/fonts'
            admin_images:
                base_path:  'assets/admin/images'
            admin_js:
                base_path:  'assets/admin/js'
            kendo_ui:
                base_path:  'assets/admin/vendor/kendo'
            admin_vendor:
                base_path:  'assets/admin/vendor'
            # Plugins cdn
            multiselect:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/'
            handlebars:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.12/'
            datetimepicker:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/'
            daterangepicker:
                base_urls: 'https://cdn.jsdelivr.net/npm/daterangepicker/'
            momentjs:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/'
            image_picker:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/'
            idletimer:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/jquery-idletimer/1.0.0/'
            intl_tel_input:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/12.4.0/'
            pace:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/'
            fine_uploader:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/file-uploader/5.16.0/all.fine-uploader/'
            date_picker:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/'
            jquery_form:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/'
            bootstrap:
                base_urls: 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/'
            alertify:
                base_urls: 'https://cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/'
            fontawesome:
                base_urls: 'https://use.fontawesome.com/releases/v5.1.0/'
            jquery:
                base_urls: 'https://code.jquery.com/'
            popper:
                base_urls: 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/'
