framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    # session configuration
    session:
        gc_maxlifetime: '%session_life_time%'
    # templating configuration
    templating:
        engines: ['twig', 'php']
    # fragments configuration
    fragments:
        enabled: false
    # esi configuration
    esi:
        enabled: true
    # php errors configuration
    php_errors:
        log: true
    # cache configuration
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
