security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha512

    role_hierarchy:
        ROLE_USER:                          ROLE_USER
        ROLE_EMMOBILIER_USER:               ROLE_EMMOBILIER_USER
        ROLE_RESIDENCE_USER:                ROLE_RESIDENCE_USER
        ROLE_IMMOSQUARE_USER:               ROLE_IMMOSQUARE_USER
        ROLE_SUPER_ADMIN:                   [ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_AGENCY_MANAGER:                ROLE_AGENCY_MANAGER
        ROLE_DELIVERY_TIME_MANAGER:         ROLE_DELIVERY_TIME_MANAGER
        ROLE_HOLIDAYS_MANAGER:              ROLE_HOLIDAYS_MANAGER
        ROLE_INVOICE_MANAGER:               ROLE_INVOICE_MANAGER
        ROLE_NETWORK_MANAGER:               ROLE_NETWORK_MANAGER
        ROLE_ORDER_MANAGER:                 ROLE_ORDER_MANAGER
        ROLE_PRODUCTION_MANAGER:            ROLE_PRODUCTION_MANAGER
        ROLE_PROMO_MANAGER:                 ROLE_PROMO_MANAGER
        ROLE_RETOUCH_MANAGER:               ROLE_RETOUCH_MANAGER
        ROLE_TRANSACTION_MANAGER:           ROLE_TRANSACTION_MANAGER
        ROLE_USER_MANAGER:                  ROLE_USER_MANAGER
    providers:
        default_user_provider:
            id:                             fos_user.user_provider.username_email
        admin_user_provider:
            id:                             user_provider.username_email.admin
        emmobilier_user_provider:
            id:                             user_provider.username_email.emmobilier
        residence_user_provider:
            id:                             user_provider.username_email.residence
    firewalls:
        # immosquare secure area (API Validation with header)
        immosquare_secure_area:
            pattern:                        ^/api
            provider:                       default_user_provider
            guard:
                authenticators:
                    - App\Security\APIAuthenticator
                entry_point: App\Security\APIAuthenticator
            stateless: true
        # emmobilier secure area (Traditional form)
        emmobilier_secure_area:
            pattern:                        ^/emmobilier
            form_login:
                provider:                   emmobilier_user_provider
                login_path:                 /emmobilier/login
                check_path:                 /emmobilier/login_check
                csrf_token_generator:       security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                success_handler:            authentication_emmobilier_login_success_handler
            logout:
                path:                       /emmobilier/logout
                target:                     /emmobilier/login
                invalidate_session:         false
                handlers:                   [authentication_logout_success_handler]
            remember_me:
                secret:                     '%kernel.secret%'
                lifetime:                   604800 # 1 week in seconds
                path:                       /emmobilier/
            logout_on_user_change:          true
            anonymous:                      true
        # Residence secure area (Traditional form)
        # Activate this config when you finish developing Residence app
#        residence_secure_area:
#            pattern:                        ^/residence
#            form_login:
#                provider:                   residence_user_provider
#                login_path:                 /residence/login
#                check_path:                 /residence/login_check
#                csrf_token_generator:       security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
#                success_handler:            authentication_residence_login_success_handler
#            logout:
#                path:                       /residence/logout
#                target:                     /residence/login
#                invalidate_session:         false
#                handlers:                   [authentication_logout_success_handler]
#            remember_me:
#                secret:                     '%kernel.secret%'
#                lifetime:                   604800 # 1 week in seconds
#                path:                       /
#            anonymous:                      true
        # Admin secure area (Traditional form)
        admin_secure_area:
            pattern:                        ^/admin
            form_login:
                provider:                   admin_user_provider
                login_path:                 /admin/login
                check_path:                 /admin/login_check
                csrf_token_generator:       security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                success_handler:            authentication_admin_login_success_handler
            logout:
                path:                       /admin/logout
                target:                     /admin/login
                invalidate_session:         false
            remember_me:
                secret:                     '%kernel.secret%'
                lifetime:                   604800 # 1 week in seconds
                path:                       /admin/
            anonymous:                      true
            logout_on_user_change:          true
    # Access control section
    access_control:
        # Admin space
        - { path: ^/admin/login$, role:                IS_AUTHENTICATED_ANONYMOUSLY }
        # Emmobilier space
        - { path: ^/emmobilier/login$, role:           IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/emmobilier/register$, role:        IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/emmobilier/resetting$, role:       IS_AUTHENTICATED_ANONYMOUSLY }
        # Residence space
#        - { path: ^/residence/login$, role:           IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/residence/register$, role:        IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/residence/resetting$, role:       IS_AUTHENTICATED_ANONYMOUSLY }