version: '3.7'
services:
  mysql:
     image: mysql:8.0
     restart: on-failure
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: emmobilier
       MYSQL_USER: emmobilier
       MYSQL_PASSWORD: change_me
       PMA_HOST: mysql
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './public:/var/www/html/public'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
     - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1001:1001
