#####################################################
#                                                   #
#       Admin section configuration file            #
#                                                   #
#####################################################
# Script controllers
script_controllers:
  resource: ../../src/Controller/script/
  type: annotation
  prefix: /script

