<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = 'latech/emmobilier_v2';
    const VERSIONS = array (
  'alchemy/binary-driver' => '5.0.0@6ccde0e19e81e54da77b08da1a176d43e089f3a3',
  'beelab/recaptcha2-bundle' => 'v2.0.2@04bdcf6ee7a2387673dc3681ca94da75293c5f03',
  'behat/transliterator' => 'v1.2.0@826ce7e9c2a6664c0d1f381cbb38b1fb80a7ee2c',
  'doctrine/annotations' => 'v1.6.0@c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5',
  'doctrine/cache' => 'v1.8.0@d768d58baee9a4862ca783840eca1b9add7a7f57',
  'doctrine/collections' => 'v1.5.0@a01ee38fcd999f34d9bfbcee59dbda5105449cbf',
  'doctrine/common' => 'v2.9.0@a210246d286c77d2b89040f8691ba7b3a713d2c1',
  'doctrine/dbal' => 'v2.8.0@5140a64c08b4b607b9bedaae0cedd26f04a0e621',
  'doctrine/doctrine-bundle' => '1.9.1@703fad32e4c8cbe609caf45a71a1d4266c830f0f',
  'doctrine/doctrine-cache-bundle' => '1.3.3@4c8e363f96427924e7e519c5b5119b4f54512697',
  'doctrine/doctrine-migrations-bundle' => 'v1.3.1@a9e506369f931351a2a6dd2aef588a822802b1b7',
  'doctrine/event-manager' => 'v1.0.0@a520bc093a0170feeb6b14e9d83f3a14452e64b3',
  'doctrine/inflector' => 'v1.3.0@5527a48b7313d15261292c149e55e26eae771b0a',
  'doctrine/instantiator' => '1.1.0@185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.8.1@215438c0eef3e5f9b7da7d09c6b90756071b43e6',
  'doctrine/orm' => 'v2.6.2@d2b4dd71d2a276edd65d0c170375b445f8a4a4a8',
  'doctrine/persistence' => 'v1.0.1@af1ec238659a83e320f03e0e454e200f689b4b97',
  'doctrine/reflection' => 'v1.0.0@02538d3f95e88eb397a5f86274deb2c6175c2ab6',
  'egulias/email-validator' => '2.1.6@0578b32b30b22de3e8664f797cf846fc9246f786',
  'evenement/evenement' => 'v2.1.0@6ba9a777870ab49f417e703229d53931ed40fd7a',
  'friendsofsymfony/ckeditor-bundle' => '2.1.0@7ba78735ea75b9a6d4de403d7aced6c993a0557a',
  'friendsofsymfony/jsrouting-bundle' => '2.2.1@fce90c6d283f46e7ae1beb39c9c018c1a702442e',
  'friendsofsymfony/user-bundle' => 'v2.1.2@1049935edd24ec305cc6cfde1875372fa9600446',
  'gedmo/doctrine-extensions' => 'v2.4.36@87c78ff9fd4b90460386f753d95622f6fbbfcb27',
  'google/recaptcha' => '1.2.1@e7add3be59211482ecdb942288f52da64a35f61a',
  'gregwar/captcha' => 'v1.1.7@cf953dd79748406e0292cea8c565399681e4d345',
  'gregwar/captcha-bundle' => 'v2.0.5@980afdc10a4a3350a3d64811da08915dd002ed4c',
  'guzzlehttp/guzzle' => '6.3.3@407b0cb880ace85c9b63c5f9551db498cb2d50ba',
  'guzzlehttp/promises' => 'v1.3.1@a59da6cf61d80060647ff4d3eb2c03a2bc694646',
  'guzzlehttp/psr7' => '1.4.2@f5b8a8512e2b58b0071a7280e39f14f72e05d87c',
  'imagine/imagine' => 'v0.7.1@a9a702a946073cbca166718f1b02a1e72d742daa',
  'jdorn/sql-formatter' => 'v1.2.17@64990d96e0959dff8e059dfcdc1af130728d92bc',
  'jean85/pretty-package-versions' => '1.2@75c7effcf3f77501d0e0caa75111aff4daa0dd48',
  'jms/metadata' => '1.6.0@6a06970a10e0a532fb52d3959547123b84a3b3ab',
  'knplabs/knp-components' => 'v1.3.10@fc1755ba2b77f83a3d3c99e21f3026ba2a1429be',
  'knplabs/knp-paginator-bundle' => 'v2.8.0@f4ece5b347121b9fe13166264f197f90252d4bd2',
  'markbaker/complex' => '1.4.7@1ea674a8308baf547cbcbd30c5fcd6d301b7c000',
  'monolog/monolog' => '1.23.0@fd8c787753b3a2ad11bc60c063cff1358a32a3b4',
  'neutron/temporary-filesystem' => '2.3.0@694aa3885f653dd429584e825ffbab79441d285f',
  'ocramius/package-versions' => '1.3.0@4489d5002c49d55576fa0ba786f42dbb009be46f',
  'ocramius/proxy-manager' => '2.1.1@e18ac876b2e4819c76349de8f78ccc8ef1554cd7',
  'paragonie/random_compat' => 'v2.0.17@29af24f25bab834fcbb38ad2a69fa93b867e070d',
  'php-ffmpeg/php-ffmpeg' => 'v0.14@f9cc3d0c429fade5a144db674272eb8b48db8dce',
  'phpoffice/phpspreadsheet' => '1.5.0@2dfd06c59825914a1a325f2a2ed13634b9d8c411',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'royopa/fpdf-symfony2' => '3.0@b178dc5926b761adcf5a8065b150ab4f4fd75e65',
  'sensio/framework-extra-bundle' => 'v5.2.1@535b56b7b0325e87b15b9c57bd3631ae2a0b9f16',
  'sentry/sentry' => '1.9.2@6b4c80ee1f5d9d5ab5bae949f4eb5d758a0bf64b',
  'sentry/sentry-symfony' => '2.0.3@044f6c37484520def283ff17e13af555a02f20be',
  'setasign/fpdf' => '1.8.1@2c68c9e6c034ac3187d25968790139a73184cdb1',
  'setasign/fpdi' => '1.6.2@a6ad58897a6d97cc2d2cd2adaeda343b25a368ea',
  'setasign/fpdi-fpdf' => '1.6.2@a5dda72b78253c0e9e4d644e6e3af4b94662e27e',
  'swiftmailer/swiftmailer' => 'v6.1.3@8ddcb66ac10c392d3beb54829eef8ac1438595f4',
  'symfony/asset' => 'v3.4.17@ec2e33f26b40975c179742abb5c94796e017d9be',
  'symfony/cache' => 'v3.4.17@4f29972d3fae5febec5c18db70e7dd2957e74ad6',
  'symfony/class-loader' => 'v3.4.17@f31333bdff54c7595f834d510a6d2325573ddb36',
  'symfony/config' => 'v3.4.17@e5389132dc6320682de3643091121c048ff796b3',
  'symfony/console' => 'v3.4.17@3b2b415d4c48fbefca7dc742aa0a0171bfae4e0b',
  'symfony/debug' => 'v3.4.17@0a612e9dfbd2ccce03eb174365f31ecdca930ff6',
  'symfony/dependency-injection' => 'v3.4.17@aea20fef4e92396928b5db175788b90234c0270d',
  'symfony/doctrine-bridge' => 'v3.4.17@668dfe7a1cfa94b463d26ef1cbba14536cae8fc6',
  'symfony/event-dispatcher' => 'v3.4.17@b2e1f19280c09a42dc64c0b72b80fe44dd6e88fb',
  'symfony/expression-language' => 'v3.4.17@d60e37ab9838338d959f2cc177a66cf498293788',
  'symfony/filesystem' => 'v3.4.17@d69930fc337d767607267d57c20a7403d0a822a4',
  'symfony/finder' => 'v3.4.17@54ba444dddc5bd5708a34bd095ea67c6eb54644d',
  'symfony/flex' => 'v1.1.1@9fb60f232af0764d58002e7872acb43a74506d25',
  'symfony/form' => 'v3.4.17@7ca50e2324b6bc3ef4c90565bc3f1a0513bfb22e',
  'symfony/framework-bundle' => 'v3.4.17@3736bf6f3578613a010954ee66c597e7b1bed75b',
  'symfony/http-foundation' => 'v3.4.17@3a4498236ade473c52b92d509303e5fd1b211ab1',
  'symfony/http-kernel' => 'v3.4.17@a0944a9a1d8845da724236cde9a310964acadb1c',
  'symfony/inflector' => 'v3.4.17@129ac0c59e516f5fe210efe51a44f79ab9925c16',
  'symfony/intl' => 'v3.4.17@f6dd4898d2872719e9fe723859625ad41e231b31',
  'symfony/monolog-bridge' => 'v3.4.17@4c668eebb35936b5058c8878f2e208c74697f70b',
  'symfony/monolog-bundle' => 'v3.2.0@8781649349fe418d51d194f8c9d212c0b97c40dd',
  'symfony/options-resolver' => 'v3.4.17@1cf7d8e704a9cc4164c92e430f2dfa3e6983661d',
  'symfony/orm-pack' => 'v1.0.5@1b58f752cd917a08c9c8df020781d9c46a2275b1',
  'symfony/polyfill-apcu' => 'v1.9.0@19e1b73bf255265ad0b568f81766ae2a3266d8d2',
  'symfony/polyfill-ctype' => 'v1.9.0@e3d826245268269cd66f8326bd8bc066687b4a19',
  'symfony/polyfill-intl-icu' => 'v1.9.0@f22a90256d577c7ef7efad8df1f0201663d57644',
  'symfony/polyfill-mbstring' => 'v1.9.0@d0cd638f4634c16d8df4508e847f14e9e43168b8',
  'symfony/process' => 'v3.4.17@1dc2977afa7d70f90f3fefbcd84152813558910e',
  'symfony/property-access' => 'v3.4.17@a62b882330f24b43f4409e50a0692aa433947460',
  'symfony/routing' => 'v3.4.17@585f6e2d740393d546978769dd56e496a6233e0b',
  'symfony/security' => 'v3.4.17@c2b1444d0d56a086c2b0438e8b9024e9b3441e05',
  'symfony/security-bundle' => 'v3.4.17@fab50cef3b3187e0da05eb3c34cf281573cb9b90',
  'symfony/serializer' => 'v3.4.17@8bc00ef47a428bfebc4641f29d158e7c56137fcb',
  'symfony/swiftmailer-bundle' => 'v3.2.3@7bd5de67552ee3f7e04df89d662d41eba346dc83',
  'symfony/templating' => 'v3.4.17@d8693ae4a45f8bb8eae5b1df89c00ec236c1e457',
  'symfony/translation' => 'v3.4.17@94bc3a79008e6640defedf5e14eb3b4f20048352',
  'symfony/twig-bridge' => 'v3.4.17@8a852d57a609982043a50987adfcdd3e8ccc76f9',
  'symfony/twig-bundle' => 'v3.4.17@6e6e092903eca775f83ac52ddfe174ba8d5dbc8d',
  'symfony/validator' => 'v3.4.17@9f8dbf0dceb03815c3160a279bf8cf4f8018a1c5',
  'symfony/var-dumper' => 'v3.4.17@ff8ac19e97e5c7c3979236b584719a1190f84181',
  'symfony/yaml' => 'v3.4.17@640b6c27fed4066d64b64d5903a86043f4a4de7f',
  'twig/twig' => 'v2.5.0@6a5f676b77a90823c2d4eaf76137b771adf31323',
  'vich/uploader-bundle' => '1.8.3@37bc4b3264a0e22608a56406d5019b26864b9553',
  'willdurand/jsonp-callback-validator' => 'v1.1.0@1a7d388bb521959e612ef50c5c7b1691b097e909',
  'zendframework/zend-code' => '3.3.1@c21db169075c6ec4b342149f446e7b7b724f95eb',
  'zendframework/zend-eventmanager' => '3.2.1@a5e2583a211f73604691586b8406ff7296a946dd',
  'doctrine/data-fixtures' => 'v1.3.1@3a1e2c3c600e615a2dffe56d4ca0875cc5233e0a',
  'doctrine/doctrine-fixtures-bundle' => '3.0.2@7fc29d2b18c61ed99826b21fbfd1ff9969cc2e7f',
  'fzaninotto/faker' => 'v1.8.0@f72816b43e74063c8b10357394b6bba8cb1c10de',
  'h4cc/wkhtmltopdf-amd64' => '0.12.4@4e2ab2d032a5d7fbe2a741de8b10b8989523c95b',
  'nikic/php-parser' => 'v4.1.0@d0230c5c77a7e3cfa69446febf340978540958c0',
  'symfony/browser-kit' => 'v3.4.17@f6668d1a6182d5a8dec65a1c863a4c1d963816c0',
  'symfony/css-selector' => 'v3.4.17@3503415d4aafabc31cd08c3a4ebac7f43fde8feb',
  'symfony/dom-crawler' => 'v3.4.17@c705bee03ade5b47c087807dd9ffaaec8dda2722',
  'symfony/dotenv' => 'v3.4.17@fcc8c8c73899e65ec528aac439c49e7929cdb87b',
  'symfony/lts' => 'v3@3a4e88df038e3197e6b66d091d2495fd7d255c0b',
  'symfony/maker-bundle' => 'v1.8.0@26643943fe19b5b47d620744907f09d1d6b3f06f',
  'symfony/phpunit-bridge' => 'v3.4.17@76e013a98031356604e5a730c9eb22713dc4dda4',
  'symfony/profiler-pack' => 'v1.0.3@fa2e2dad522a3bef322196abad28ffce6d0fdbc5',
  'symfony/stopwatch' => 'v3.4.17@05e52a39de52ba690aebaed462b2bc8a9649f0a4',
  'symfony/web-profiler-bundle' => 'v3.4.17@f2f0865ed7a3f4a154633ed376e363b8d55d8bdb',
  'symfony/web-server-bundle' => 'v3.4.17@dad213bcae92c8ed53facca633c7e79fb2e0e9d6',
  'willdurand/faker-bundle' => '1.4.1@f2feb720d83dda9e9022b67c7a1625a6e9df1742',
  'symfony/polyfill-iconv' => '*@',
  'symfony/polyfill-php70' => '*@',
  'symfony/polyfill-php56' => '*@',
  'latech/emmobilier_v2' => '1.0.0@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: cannot detect its version'
        );
    }
}
