<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Raven_' => array($vendorDir . '/sentry/sentry/lib'),
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'Neutron' => array($vendorDir . '/neutron/temporary-filesystem/src'),
    'Metadata\\' => array($vendorDir . '/jms/metadata/src'),
    'Knp\\Component' => array($vendorDir . '/knplabs/knp-components/src'),
    'JsonpCallbackValidator' => array($vendorDir . '/willdurand/jsonp-callback-validator/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'FPDF_' => array($vendorDir . '/royopa/fpdf-symfony2/lib'),
    'FFMpeg' => array($vendorDir . '/php-ffmpeg/php-ffmpeg/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Behat\\Transliterator' => array($vendorDir . '/behat/transliterator/src'),
    'Bazinga\\Bundle\\FakerBundle' => array($vendorDir . '/willdurand/faker-bundle'),
    'Alchemy' => array($vendorDir . '/alchemy/binary-driver/src'),
);
