#####################################################
#                                                   #
#        Default fallback if env not set            #
#                                                   #
#####################################################
parameters:
  ###> domaine/env ###
  env(TRUSTED_PROXIES): ~
  env(TRUSTED_HOSTS): ~
  ###< domaine/env ###

  ###> symfony/framework-bundle ###
  env(APP_ENV): dev
  env(APP_SECRET): ""
  ###< symfony/framework-bundle ###

  ###> symfony/swiftmailer-bundle ###
  # For Gmail as a transport, use: "gmail://username:password@localhost"
  # For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
  # Delivery is disabled by default via "null://localhost"
  env(MAILER_URL): null://localhost
  ###< symfony/swiftmailer-bundle ###

  ###> doctrine/doctrine-bundle ###
  # Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
  # For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data.db"
  # Configure your db driver and server_version in config/packages/doctrine.yaml
  # DATABASE_URL=sqlite:///%kernel.project_dir%/app.db
  env(DATABASE_URL): sqlite:///%kernel.project_dir%/app.db

  ###< doctrine/doctrine-bundle ###

  ###> beelab/recaptcha2-bundle ###
  env(APP_RECAPTCHA_SITE_KEY): ""
  env(APP_RECAPTCHA_SECRET): ""
  ###< beelab/recaptcha2-bundle ###

  ###> sentry/sentry-symfony ###
  env(SENTRY_DSN): ""
  ###< sentry/sentry-symfony ###