#####################################################
#                                                   #
#        Extract configuration                      #
#                                                   #
#####################################################
parameters:
    extract_path:    '%kernel.project_dir%/public/extract'
