<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190109111357 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
	    if ($this->connection->getDatabasePlatform()->getName() !== 'postgresql'){
		    print "'postgresql' Migration ignored .";
		    return;
	    }
	    
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE ext_log_entries_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE production_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE wallet_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE field_renovation_choices_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fos_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE picture_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE field_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organization_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE picture_details_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fos_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE invoice_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE retouch_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE field_renovation_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE field_choices_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE picture_counter_per_retouch_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE param_collection_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE promo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE emmo_transaction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE field_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE emmo_order_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE holidays_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE picture_discount_per_retouch_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE field_details_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE order_delivery_time_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE photo_retouching_pricing_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE ext_translations (id SERIAL NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(255) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX translations_lookup_idx ON ext_translations (locale, object_class, foreign_key)');
        $this->addSql('CREATE UNIQUE INDEX lookup_unique_idx ON ext_translations (locale, object_class, field, foreign_key)');
        $this->addSql('CREATE TABLE ext_log_entries (id INT NOT NULL, action VARCHAR(8) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data TEXT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX log_class_lookup_idx ON ext_log_entries (object_class)');
        $this->addSql('CREATE INDEX log_date_lookup_idx ON ext_log_entries (logged_at)');
        $this->addSql('CREATE INDEX log_user_lookup_idx ON ext_log_entries (username)');
        $this->addSql('CREATE INDEX log_version_lookup_idx ON ext_log_entries (object_id, object_class, version)');
        $this->addSql('COMMENT ON COLUMN ext_log_entries.data IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE production (id INT NOT NULL, country VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE wallet (id INT NOT NULL, client_id INT DEFAULT NULL, current_amount NUMERIC(10, 2) NOT NULL, last_update TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7C68921F19EB6921 ON wallet (client_id)');
        $this->addSql('CREATE TABLE field_renovation_choices (id INT NOT NULL, type_id INT DEFAULT NULL, picture_path TEXT DEFAULT NULL, uuid VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5F23A48EC54C8C93 ON field_renovation_choices (type_id)');
        $this->addSql('CREATE TABLE fos_user (id INT NOT NULL, organization_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, image_name VARCHAR(255) DEFAULT NULL, first_name VARCHAR(200) DEFAULT NULL, last_name VARCHAR(150) DEFAULT NULL, email_secondary VARCHAR(255) DEFAULT NULL, register_code VARCHAR(200) DEFAULT NULL, language VARCHAR(200) DEFAULT NULL, user_directory TEXT DEFAULT NULL, api_token TEXT DEFAULT NULL, facebook_id VARCHAR(255) DEFAULT NULL, facebook_access_token VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, google_access_token VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, receive_newsletter BOOLEAN DEFAULT NULL, receive_targeted_emails_from_promotion BOOLEAN DEFAULT NULL, type VARCHAR(50) DEFAULT NULL, billing_address_first_name VARCHAR(70) DEFAULT NULL, billing_address_last_name VARCHAR(100) DEFAULT NULL, billing_address_address VARCHAR(255) DEFAULT NULL, billing_address_country VARCHAR(100) DEFAULT NULL, billing_address_city VARCHAR(150) DEFAULT NULL, billing_address_zip_code VARCHAR(20) DEFAULT NULL, billing_address_phone VARCHAR(50) DEFAULT NULL, billing_address_company VARCHAR(200) DEFAULT NULL, billing_address_network_name VARCHAR(255) DEFAULT NULL, billing_address_secondary_address VARCHAR(255) DEFAULT NULL, billing_address_corporate_name VARCHAR(255) DEFAULT NULL, billing_address_tva VARCHAR(200) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_957A647992FC23A8 ON fos_user (username_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_957A6479A0D96FBF ON fos_user (email_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_957A6479C05FB297 ON fos_user (confirmation_token)');
        $this->addSql('CREATE INDEX IDX_957A647932C8A3DE ON fos_user (organization_id)');
        $this->addSql('COMMENT ON COLUMN fos_user.roles IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE fos_user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY(user_id, group_id))');
        $this->addSql('CREATE INDEX IDX_B3C77447A76ED395 ON fos_user_user_group (user_id)');
        $this->addSql('CREATE INDEX IDX_B3C77447FE54D947 ON fos_user_user_group (group_id)');
        $this->addSql('CREATE TABLE picture (id INT NOT NULL, order_id INT DEFAULT NULL, picture_name VARCHAR(255) DEFAULT NULL, picture_path TEXT DEFAULT NULL, painted_picture_path TEXT DEFAULT NULL, painted_picture_path_thumb TEXT DEFAULT NULL, picture_path_thumb TEXT DEFAULT NULL, picture_directory VARCHAR(150) DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, commentary TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_16DB4F898D9F6D38 ON picture (order_id)');
        $this->addSql('CREATE TABLE field (id INT NOT NULL, disabled_on_id INT DEFAULT NULL, field_group_id INT DEFAULT NULL, name VARCHAR(200) NOT NULL, label_text VARCHAR(255) DEFAULT NULL, empty_data VARCHAR(255) DEFAULT NULL, mapped BOOLEAN DEFAULT NULL, price NUMERIC(5, 2) DEFAULT NULL, add_the_price_when_value_equals_to VARCHAR(200) DEFAULT NULL, field_type VARCHAR(200) NOT NULL, order_number INT NOT NULL, htmlclass VARCHAR(150) DEFAULT NULL, disabled BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5BF545585E237E06 ON field (name)');
        $this->addSql('CREATE INDEX IDX_5BF5455823D615C7 ON field (disabled_on_id)');
        $this->addSql('CREATE INDEX IDX_5BF54558286C5E8A ON field (field_group_id)');
        $this->addSql('CREATE TABLE field_field_choices (field_id INT NOT NULL, field_choices_id INT NOT NULL, PRIMARY KEY(field_id, field_choices_id))');
        $this->addSql('CREATE INDEX IDX_77FBC7C0443707B0 ON field_field_choices (field_id)');
        $this->addSql('CREATE INDEX IDX_77FBC7C01BB4B0B9 ON field_field_choices (field_choices_id)');
        $this->addSql('CREATE TABLE field_field_renovation_type (field_id INT NOT NULL, field_renovation_type_id INT NOT NULL, PRIMARY KEY(field_id, field_renovation_type_id))');
        $this->addSql('CREATE INDEX IDX_7F073864443707B0 ON field_field_renovation_type (field_id)');
        $this->addSql('CREATE INDEX IDX_7F0738649FA1BE24 ON field_field_renovation_type (field_renovation_type_id)');
        $this->addSql('CREATE TABLE organization (id INT NOT NULL, owner_id INT NOT NULL, network_id INT DEFAULT NULL, registration_code VARCHAR(255) DEFAULT NULL, discr VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C1EE637CB82B2744 ON organization (registration_code)');
        $this->addSql('CREATE INDEX IDX_C1EE637C7E3C61F9 ON organization (owner_id)');
        $this->addSql('CREATE INDEX IDX_C1EE637C34128B91 ON organization (network_id)');
        $this->addSql('CREATE TABLE picture_details (id INT NOT NULL, retouch_id INT NOT NULL, picture_id INT DEFAULT NULL, param_id INT DEFAULT NULL, returned_picture_id INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, price NUMERIC(10, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6F00FF58B0C9087F ON picture_details (retouch_id)');
        $this->addSql('CREATE INDEX IDX_6F00FF58EE45BDBF ON picture_details (picture_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6F00FF585647C863 ON picture_details (param_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6F00FF58505D3329 ON picture_details (returned_picture_id)');
        $this->addSql('CREATE TABLE fos_group (id INT NOT NULL, name VARCHAR(180) NOT NULL, roles TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B019DDB5E237E06 ON fos_group (name)');
        $this->addSql('COMMENT ON COLUMN fos_group.roles IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE invoice (id INT NOT NULL, organization_id INT DEFAULT NULL, client_id INT DEFAULT NULL, invoice_number NUMERIC(10, 0) DEFAULT NULL, pdf_file_name VARCHAR(200) DEFAULT NULL, total_amount_paid NUMERIC(10, 2) DEFAULT NULL, total_amount NUMERIC(10, 2) DEFAULT NULL, tax_percentage NUMERIC(5, 2) DEFAULT NULL, reduction_percentage NUMERIC(5, 2) DEFAULT NULL, total_reduction_on_pictures NUMERIC(3, 0) DEFAULT NULL, total_reduction_amount NUMERIC(10, 2) DEFAULT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(150) DEFAULT NULL, app_type VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9065174432C8A3DE ON invoice (organization_id)');
        $this->addSql('CREATE INDEX IDX_9065174419EB6921 ON invoice (client_id)');
        $this->addSql('CREATE TABLE retouch (id INT NOT NULL, title VARCHAR(200) DEFAULT NULL, description TEXT DEFAULT NULL, order_number INT DEFAULT NULL, retouch_code VARCHAR(200) DEFAULT NULL, app_type VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE field_renovation_type (id INT NOT NULL, type_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE field_choices (id INT NOT NULL, choice_label VARCHAR(255) NOT NULL, choice_value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE picture_counter_per_retouch (id INT NOT NULL, picture_counter_id INT DEFAULT NULL, retouch_id INT DEFAULT NULL, image_counter_limit NUMERIC(5, 0) NOT NULL, image_counter_limit_with_reduction NUMERIC(5, 0) NOT NULL, image_counter_reduction NUMERIC(5, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8412C9FED03EB2E4 ON picture_counter_per_retouch (picture_counter_id)');
        $this->addSql('CREATE INDEX IDX_8412C9FEB0C9087F ON picture_counter_per_retouch (retouch_id)');
        $this->addSql('CREATE TABLE param_collection (id INT NOT NULL, elements TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN param_collection.elements IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE promo (id INT NOT NULL, organization_id INT DEFAULT NULL, promo_code VARCHAR(150) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, expired BOOLEAN DEFAULT NULL, promo_type VARCHAR(150) NOT NULL, discr VARCHAR(255) NOT NULL, has_number_of_use BOOLEAN DEFAULT NULL, use_limit NUMERIC(5, 0) DEFAULT NULL, use_limit_per_user NUMERIC(5, 0) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B0139AFB32C8A3DE ON promo (organization_id)');
        $this->addSql('CREATE TABLE promo_user (promo_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(promo_id, user_id))');
        $this->addSql('CREATE INDEX IDX_C70A754FD0C07AFF ON promo_user (promo_id)');
        $this->addSql('CREATE INDEX IDX_C70A754FA76ED395 ON promo_user (user_id)');
        $this->addSql('CREATE TABLE emmo_transaction (id INT NOT NULL, client_id INT DEFAULT NULL, wallet_id INT DEFAULT NULL, order_id INT DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, transaction_number INT DEFAULT NULL, transaction_ext_number TEXT DEFAULT NULL, status_code VARCHAR(255) DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, log_response TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paid BOOLEAN DEFAULT NULL, card_number VARCHAR(50) DEFAULT NULL, card_brand VARCHAR(50) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5468AD7219EB6921 ON emmo_transaction (client_id)');
        $this->addSql('CREATE INDEX IDX_5468AD72712520F3 ON emmo_transaction (wallet_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5468AD728D9F6D38 ON emmo_transaction (order_id)');
        $this->addSql('COMMENT ON COLUMN emmo_transaction.log_response IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE field_group (id INT NOT NULL, label_text VARCHAR(255) NOT NULL, position VARCHAR(50) NOT NULL, order_number INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE field_group_retouch (field_group_id INT NOT NULL, retouch_id INT NOT NULL, PRIMARY KEY(field_group_id, retouch_id))');
        $this->addSql('CREATE INDEX IDX_94277A2F286C5E8A ON field_group_retouch (field_group_id)');
        $this->addSql('CREATE INDEX IDX_94277A2FB0C9087F ON field_group_retouch (retouch_id)');
        $this->addSql('CREATE TABLE emmo_order (id INT NOT NULL, client_id INT DEFAULT NULL, affected_to_id INT DEFAULT NULL, id_promo INT DEFAULT NULL, production_id INT DEFAULT NULL, delivery_time_id INT DEFAULT NULL, order_number INT DEFAULT NULL, order_status VARCHAR(50) NOT NULL, send_email BOOLEAN NOT NULL, upload_folder TEXT DEFAULT NULL, total_amount NUMERIC(10, 2) NOT NULL, tax_percentage NUMERIC(4, 2) DEFAULT NULL, reduction_percentage NUMERIC(5, 2) DEFAULT NULL, total_reduction_on_pictures NUMERIC(3, 0) DEFAULT NULL, total_reduction_amount NUMERIC(10, 2) DEFAULT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deliverance_date DATE DEFAULT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deletedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, app_type VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_81AB967019EB6921 ON emmo_order (client_id)');
        $this->addSql('CREATE INDEX IDX_81AB9670F3310D50 ON emmo_order (affected_to_id)');
        $this->addSql('CREATE INDEX IDX_81AB96705E96DBCB ON emmo_order (id_promo)');
        $this->addSql('CREATE INDEX IDX_81AB9670ECC6147F ON emmo_order (production_id)');
        $this->addSql('CREATE INDEX IDX_81AB967054F462E5 ON emmo_order (delivery_time_id)');
        $this->addSql('CREATE TABLE order_invoice (order_id INT NOT NULL, invoice_id INT NOT NULL, PRIMARY KEY(order_id, invoice_id))');
        $this->addSql('CREATE INDEX IDX_661FBE0F8D9F6D38 ON order_invoice (order_id)');
        $this->addSql('CREATE INDEX IDX_661FBE0F2989F1FD ON order_invoice (invoice_id)');
        $this->addSql('CREATE TABLE holidays (id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE picture_discount_per_retouch (id INT NOT NULL, retouch_id INT DEFAULT NULL, picture_discount_id INT DEFAULT NULL, reduction NUMERIC(5, 2) NOT NULL, image_limit NUMERIC(5, 0) DEFAULT NULL, image_limit_per_order NUMERIC(5, 0) DEFAULT NULL, image_limit_per_user NUMERIC(5, 0) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_935D6AA4B0C9087F ON picture_discount_per_retouch (retouch_id)');
        $this->addSql('CREATE INDEX IDX_935D6AA4D23424FC ON picture_discount_per_retouch (picture_discount_id)');
        $this->addSql('CREATE TABLE field_details (id INT NOT NULL, picture_detail_id INT DEFAULT NULL, field_id INT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9C022E2AD10E8F05 ON field_details (picture_detail_id)');
        $this->addSql('CREATE INDEX IDX_9C022E2A443707B0 ON field_details (field_id)');
        $this->addSql('CREATE TABLE order_delivery_time (id INT NOT NULL, time INT DEFAULT NULL, unit VARCHAR(200) DEFAULT NULL, order_delivery_code VARCHAR(200) DEFAULT NULL, global BOOLEAN NOT NULL, selected_by_default BOOLEAN NOT NULL, app_type VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE photo_retouching_pricing (id INT NOT NULL, retouch_id INT DEFAULT NULL, order_delivery_time_id INT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_64945F65B0C9087F ON photo_retouching_pricing (retouch_id)');
        $this->addSql('CREATE INDEX IDX_64945F6536E276F9 ON photo_retouching_pricing (order_delivery_time_id)');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921F19EB6921 FOREIGN KEY (client_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_renovation_choices ADD CONSTRAINT FK_5F23A48EC54C8C93 FOREIGN KEY (type_id) REFERENCES field_renovation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fos_user ADD CONSTRAINT FK_957A647932C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447FE54D947 FOREIGN KEY (group_id) REFERENCES fos_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture ADD CONSTRAINT FK_16DB4F898D9F6D38 FOREIGN KEY (order_id) REFERENCES emmo_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field ADD CONSTRAINT FK_5BF5455823D615C7 FOREIGN KEY (disabled_on_id) REFERENCES field (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field ADD CONSTRAINT FK_5BF54558286C5E8A FOREIGN KEY (field_group_id) REFERENCES field_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_field_choices ADD CONSTRAINT FK_77FBC7C0443707B0 FOREIGN KEY (field_id) REFERENCES field (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_field_choices ADD CONSTRAINT FK_77FBC7C01BB4B0B9 FOREIGN KEY (field_choices_id) REFERENCES field_choices (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_field_renovation_type ADD CONSTRAINT FK_7F073864443707B0 FOREIGN KEY (field_id) REFERENCES field (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_field_renovation_type ADD CONSTRAINT FK_7F0738649FA1BE24 FOREIGN KEY (field_renovation_type_id) REFERENCES field_renovation_type (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637C34128B91 FOREIGN KEY (network_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture_details ADD CONSTRAINT FK_6F00FF58B0C9087F FOREIGN KEY (retouch_id) REFERENCES retouch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture_details ADD CONSTRAINT FK_6F00FF58EE45BDBF FOREIGN KEY (picture_id) REFERENCES picture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture_details ADD CONSTRAINT FK_6F00FF585647C863 FOREIGN KEY (param_id) REFERENCES param_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture_details ADD CONSTRAINT FK_6F00FF58505D3329 FOREIGN KEY (returned_picture_id) REFERENCES picture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174432C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174419EB6921 FOREIGN KEY (client_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture_counter_per_retouch ADD CONSTRAINT FK_8412C9FED03EB2E4 FOREIGN KEY (picture_counter_id) REFERENCES promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture_counter_per_retouch ADD CONSTRAINT FK_8412C9FEB0C9087F FOREIGN KEY (retouch_id) REFERENCES retouch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo ADD CONSTRAINT FK_B0139AFB32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_user ADD CONSTRAINT FK_C70A754FD0C07AFF FOREIGN KEY (promo_id) REFERENCES promo (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_user ADD CONSTRAINT FK_C70A754FA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emmo_transaction ADD CONSTRAINT FK_5468AD7219EB6921 FOREIGN KEY (client_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emmo_transaction ADD CONSTRAINT FK_5468AD72712520F3 FOREIGN KEY (wallet_id) REFERENCES wallet (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emmo_transaction ADD CONSTRAINT FK_5468AD728D9F6D38 FOREIGN KEY (order_id) REFERENCES emmo_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_group_retouch ADD CONSTRAINT FK_94277A2F286C5E8A FOREIGN KEY (field_group_id) REFERENCES field_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_group_retouch ADD CONSTRAINT FK_94277A2FB0C9087F FOREIGN KEY (retouch_id) REFERENCES retouch (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emmo_order ADD CONSTRAINT FK_81AB967019EB6921 FOREIGN KEY (client_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emmo_order ADD CONSTRAINT FK_81AB9670F3310D50 FOREIGN KEY (affected_to_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emmo_order ADD CONSTRAINT FK_81AB96705E96DBCB FOREIGN KEY (id_promo) REFERENCES promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emmo_order ADD CONSTRAINT FK_81AB9670ECC6147F FOREIGN KEY (production_id) REFERENCES production (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emmo_order ADD CONSTRAINT FK_81AB967054F462E5 FOREIGN KEY (delivery_time_id) REFERENCES order_delivery_time (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_invoice ADD CONSTRAINT FK_661FBE0F8D9F6D38 FOREIGN KEY (order_id) REFERENCES emmo_order (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_invoice ADD CONSTRAINT FK_661FBE0F2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture_discount_per_retouch ADD CONSTRAINT FK_935D6AA4B0C9087F FOREIGN KEY (retouch_id) REFERENCES retouch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture_discount_per_retouch ADD CONSTRAINT FK_935D6AA4D23424FC FOREIGN KEY (picture_discount_id) REFERENCES promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_details ADD CONSTRAINT FK_9C022E2AD10E8F05 FOREIGN KEY (picture_detail_id) REFERENCES picture_details (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE field_details ADD CONSTRAINT FK_9C022E2A443707B0 FOREIGN KEY (field_id) REFERENCES field (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE photo_retouching_pricing ADD CONSTRAINT FK_64945F65B0C9087F FOREIGN KEY (retouch_id) REFERENCES retouch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE photo_retouching_pricing ADD CONSTRAINT FK_64945F6536E276F9 FOREIGN KEY (order_delivery_time_id) REFERENCES order_delivery_time (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
	    if ($this->connection->getDatabasePlatform()->getName() !== 'postgresql'){
		    print "'postgresql' Migration ignored .";
		    return;
	    }
	    
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE emmo_order DROP CONSTRAINT FK_81AB9670ECC6147F');
        $this->addSql('ALTER TABLE emmo_transaction DROP CONSTRAINT FK_5468AD72712520F3');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT FK_7C68921F19EB6921');
        $this->addSql('ALTER TABLE fos_user_user_group DROP CONSTRAINT FK_B3C77447A76ED395');
        $this->addSql('ALTER TABLE organization DROP CONSTRAINT FK_C1EE637C7E3C61F9');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_9065174419EB6921');
        $this->addSql('ALTER TABLE promo_user DROP CONSTRAINT FK_C70A754FA76ED395');
        $this->addSql('ALTER TABLE emmo_transaction DROP CONSTRAINT FK_5468AD7219EB6921');
        $this->addSql('ALTER TABLE emmo_order DROP CONSTRAINT FK_81AB967019EB6921');
        $this->addSql('ALTER TABLE emmo_order DROP CONSTRAINT FK_81AB9670F3310D50');
        $this->addSql('ALTER TABLE picture_details DROP CONSTRAINT FK_6F00FF58EE45BDBF');
        $this->addSql('ALTER TABLE picture_details DROP CONSTRAINT FK_6F00FF58505D3329');
        $this->addSql('ALTER TABLE field DROP CONSTRAINT FK_5BF5455823D615C7');
        $this->addSql('ALTER TABLE field_field_choices DROP CONSTRAINT FK_77FBC7C0443707B0');
        $this->addSql('ALTER TABLE field_field_renovation_type DROP CONSTRAINT FK_7F073864443707B0');
        $this->addSql('ALTER TABLE field_details DROP CONSTRAINT FK_9C022E2A443707B0');
        $this->addSql('ALTER TABLE fos_user DROP CONSTRAINT FK_957A647932C8A3DE');
        $this->addSql('ALTER TABLE organization DROP CONSTRAINT FK_C1EE637C34128B91');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_9065174432C8A3DE');
        $this->addSql('ALTER TABLE promo DROP CONSTRAINT FK_B0139AFB32C8A3DE');
        $this->addSql('ALTER TABLE field_details DROP CONSTRAINT FK_9C022E2AD10E8F05');
        $this->addSql('ALTER TABLE fos_user_user_group DROP CONSTRAINT FK_B3C77447FE54D947');
        $this->addSql('ALTER TABLE order_invoice DROP CONSTRAINT FK_661FBE0F2989F1FD');
        $this->addSql('ALTER TABLE picture_details DROP CONSTRAINT FK_6F00FF58B0C9087F');
        $this->addSql('ALTER TABLE picture_counter_per_retouch DROP CONSTRAINT FK_8412C9FEB0C9087F');
        $this->addSql('ALTER TABLE field_group_retouch DROP CONSTRAINT FK_94277A2FB0C9087F');
        $this->addSql('ALTER TABLE picture_discount_per_retouch DROP CONSTRAINT FK_935D6AA4B0C9087F');
        $this->addSql('ALTER TABLE photo_retouching_pricing DROP CONSTRAINT FK_64945F65B0C9087F');
        $this->addSql('ALTER TABLE field_renovation_choices DROP CONSTRAINT FK_5F23A48EC54C8C93');
        $this->addSql('ALTER TABLE field_field_renovation_type DROP CONSTRAINT FK_7F0738649FA1BE24');
        $this->addSql('ALTER TABLE field_field_choices DROP CONSTRAINT FK_77FBC7C01BB4B0B9');
        $this->addSql('ALTER TABLE picture_details DROP CONSTRAINT FK_6F00FF585647C863');
        $this->addSql('ALTER TABLE picture_counter_per_retouch DROP CONSTRAINT FK_8412C9FED03EB2E4');
        $this->addSql('ALTER TABLE promo_user DROP CONSTRAINT FK_C70A754FD0C07AFF');
        $this->addSql('ALTER TABLE emmo_order DROP CONSTRAINT FK_81AB96705E96DBCB');
        $this->addSql('ALTER TABLE picture_discount_per_retouch DROP CONSTRAINT FK_935D6AA4D23424FC');
        $this->addSql('ALTER TABLE field DROP CONSTRAINT FK_5BF54558286C5E8A');
        $this->addSql('ALTER TABLE field_group_retouch DROP CONSTRAINT FK_94277A2F286C5E8A');
        $this->addSql('ALTER TABLE picture DROP CONSTRAINT FK_16DB4F898D9F6D38');
        $this->addSql('ALTER TABLE emmo_transaction DROP CONSTRAINT FK_5468AD728D9F6D38');
        $this->addSql('ALTER TABLE order_invoice DROP CONSTRAINT FK_661FBE0F8D9F6D38');
        $this->addSql('ALTER TABLE emmo_order DROP CONSTRAINT FK_81AB967054F462E5');
        $this->addSql('ALTER TABLE photo_retouching_pricing DROP CONSTRAINT FK_64945F6536E276F9');
        $this->addSql('DROP SEQUENCE ext_log_entries_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE production_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE wallet_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE field_renovation_choices_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fos_user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE picture_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE field_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organization_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE picture_details_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fos_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE invoice_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE retouch_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE field_renovation_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE field_choices_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE picture_counter_per_retouch_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE param_collection_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE promo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE emmo_transaction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE field_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE emmo_order_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE holidays_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE picture_discount_per_retouch_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE field_details_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE order_delivery_time_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE photo_retouching_pricing_id_seq CASCADE');
        $this->addSql('DROP TABLE ext_translations');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE production');
        $this->addSql('DROP TABLE wallet');
        $this->addSql('DROP TABLE field_renovation_choices');
        $this->addSql('DROP TABLE fos_user');
        $this->addSql('DROP TABLE fos_user_user_group');
        $this->addSql('DROP TABLE picture');
        $this->addSql('DROP TABLE field');
        $this->addSql('DROP TABLE field_field_choices');
        $this->addSql('DROP TABLE field_field_renovation_type');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE picture_details');
        $this->addSql('DROP TABLE fos_group');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE retouch');
        $this->addSql('DROP TABLE field_renovation_type');
        $this->addSql('DROP TABLE field_choices');
        $this->addSql('DROP TABLE picture_counter_per_retouch');
        $this->addSql('DROP TABLE param_collection');
        $this->addSql('DROP TABLE promo');
        $this->addSql('DROP TABLE promo_user');
        $this->addSql('DROP TABLE emmo_transaction');
        $this->addSql('DROP TABLE field_group');
        $this->addSql('DROP TABLE field_group_retouch');
        $this->addSql('DROP TABLE emmo_order');
        $this->addSql('DROP TABLE order_invoice');
        $this->addSql('DROP TABLE holidays');
        $this->addSql('DROP TABLE picture_discount_per_retouch');
        $this->addSql('DROP TABLE field_details');
        $this->addSql('DROP TABLE order_delivery_time');
        $this->addSql('DROP TABLE photo_retouching_pricing');
    }
}
