INSERT INTO `field_group` (id, label_text, position, order_number)
VALUES (1, 'Taille', 'left', 1),
       (2, 'Format', 'left', 2),
       (3, 'Logo', 'left', 3),
       (4, 'GIF animé Avant-Après', 'left', 4),
       (5, 'Information complémentaire', 'right', 5),
       (6, 'Filigrane', 'right', 6),
       (7, 'Pour Photo-Staging 2D, besoin d''écrire :', 'right', 7),
       (9, 'Pour AMÉNAGEMENT EXTÉRIEUR, besoin d''écrire :', 'right', 7),
       (10, 'Cahier des Charges', 'right', 5),
       (11, 'Pour Photo-Staging Virtuel, besoin d''écrire :', 'right', 7),
       (12, 'Piscine extérieure', 'right', 7),
       (13,
        'Définissez pour chaque image 1 des choix de rénovation mur et/ou sol, que nous avons pris soin de présélectionner pour vous.',
        'right',
        9),
       (14, 'Ciel bleu', 'right', 10),
       (15,
        'Besoins particuliers ? Cet espace est dédié à la dépose de visuels et documents nécessaires à la retouche de votre image.',
        'right',
        7),
       (16, 'Lit non fait', 'right', 8);
