INSERT INTO `field` (id,
                     field_group_id,
                     disabled_on_id,
                     name,
                     empty_data,
                     field_type,
                     order_number,
                     disabled,
                     price,
                     add_the_price_when_value_equals_to,
                     label_text,
                     mapped,
                     htmlclass)
VALUES (1, 1, NULL, 'origin_size', 'original', 'radio', 1, 0, NULL, NULL, NULL, 1, NULL),
       (2, 1, 1, 'height', NULL, 'text', 2, 1, NULL, NULL, 'Hauteur', 1, NULL),
       (3, 1, 1, 'Width', NULL, 'text', 2, 1, NULL, NULL, 'Largeur', 1, NULL),
       (4, 1, 1, 'unit', 'px', 'radio', 2, 1, NULL, NULL, NULL, 1, 'form-unit'),
       (5, 2, NULL, 'returned_format', NULL, 'choice', 1, 0, NULL, NULL, '', 1, ''),
       (6, 3, NULL, 'logo', 'no', 'boolean', 1, 0, NULL, NULL, 'Souhaitez vous insérer votre logo?', 1, NULL),
       (7, 3, 6, 'logo_file', NULL, 'image', 2, 1, NULL, NULL, 'Choisissez votre Logo', 1, NULL),
       (8, 3, 6, 'logo_place', 'rb', 'placement', 3, 1, NULL, NULL, 'Choisissez la position du logo', 1, NULL),
       (9,
        4,
        NULL,
        'gif_animation',
        'no',
        'boolean',
        1,
        0,
        5,
        'yes',
        'Souhaitez-vous un GIF animé Avant-Après de votre image?',
        1,
        NULL),
       (10, 4, 9, 'gif_animation_config', 'original', 'radio', 2, 1, NULL, NULL, NULL, 1, NULL),
       (11,
        4,
        10,
        'gif_animation_watermark',
        NULL,
        'text_no_label',
        3,
        1,
        NULL,
        NULL,
        'Tapez votre texte personnalisé',
        1,
        NULL),
       (12, 4, 10, 'gif_animation_logo_file', NULL, 'image', 4, 1, NULL, NULL, NULL, 1, NULL),
       (13, 4, 10, 'gif_animation_place', 'rb', 'placement', 5, 1, NULL, NULL, 'Choisissez la position', 1, NULL),
       (14,
        5,
        NULL,
        'comment',
        NULL,
        'textarea',
        1,
        0,
        NULL,
        NULL,
        'Si vous deviez avoir des directives particulières à nous transmettre, écrivez ici :',
        1,
        ''),
       (15, 6, NULL, 'watermark', 'no', 'boolean', 1, 0, NULL, NULL, 'Souhaitez-vous insérer un filigrane?', 1, NULL),
       (16, 6, 15, 'watermark_text', NULL, 'text_no_label', 2, 1, NULL, NULL, 'Tapez votre filigrane', 1, NULL),
       (17, 6, 15, 'watermark_logo_file', NULL, 'image', 3, 1, NULL, NULL, 'Choisissez votre filigrane', 1, NULL),
       (18,
        6,
        15,
        'watermark_place',
        'mm',
        'placement',
        4,
        1,
        NULL,
        NULL,
        'Choisissez la position du filigrane',
        1,
        NULL),
       (19,
        7,
        NULL,
        'renovationProposal',
        'no',
        'boolean',
        1,
        0,
        NULL,
        NULL,
        'Proposition de rénovation non contractuelle.',
        1,
        NULL),
       (20,
        7,
        NULL,
        'renovationProject',
        'no',
        'boolean',
        2,
        0,
        NULL,
        NULL,
        'Projet de rénovation non contractuel.',
        1,
        NULL),
       (22,
        11,
        NULL,
        'planningProposal',
        'no',
        'boolean',
        1,
        0,
        NULL,
        NULL,
        'Proposition d''aménagement non contractuelle.',
        1,
        NULL),
       (23,
        11,
        NULL,
        'planningProject',
        'no',
        'boolean',
        2,
        0,
        NULL,
        NULL,
        'Projet d''aménagement non contractuel.',
        1,
        NULL),
       (24,
        9,
        NULL,
        'landscapingProposal',
        'no',
        'boolean',
        1,
        0,
        NULL,
        NULL,
        'Proposition d''aménagement Extérieur.',
        1,
        NULL),
       (25,
        9,
        NULL,
        'landscapingProject',
        'no',
        'boolean',
        2,
        0,
        NULL,
        NULL,
        'Projet d''aménagement Extérieur.',
        1,
        NULL),
       (26,
        10,
        NULL,
        'specifications',
        NULL,
        'textarea',
        1,
        0,
        NULL,
        NULL,
        'Décrivez succintement vos directives d''aménagement, 1 ligne par besoin.',
        1,
        NULL),
       (28, 12, NULL, 'piscine', 'no', 'boolean', 1, 0, NULL, NULL, 'Voulez-vous éclairer votre piscine ?', 1, NULL),
       (29, 13, NULL, 'field_renovation', NULL, 'image_renovation', 1, 0, NULL, NULL, NULL, 1, NULL),
       (30,
        14,
        NULL,
        'blue_sky',
        'no',
        'boolean',
        1,
        0,
        2.5,
        'yes',
        'Souhaitez-vous un ciel bleu de saison ?',
        1,
        NULL),
       (31, 15, NULL, 'document', NULL, 'file', 1, 0, NULL, NULL, '(formats : word, powerpoint, pdf, Photo)', 1, ''),
       (32, 16, NULL, 'bed', 'no', 'boolean', 1, 0, 2, 'yes', 'Souhaitez-vous faire le lit?', 1, NULL);