#########################################################################
#                                                                       #
#                           Swiftmailer configuration                   #
#                                                                       #
#########################################################################
parameters:
  # Swiftmailer Configuration
  mailer_transport: smtp
  mailer_host:      smtp.sendgrid.net
  mailer_port:      587
  mailer_encryption: tls
  mailer_user:      EMMOBILIER
  mailer_password:  12345678910E
  # Mail sender
  sender_address: 'production@emmobilier.fr'
  sender_name:    'Emmobilier webmaster'
